version: '3.8'

services:
  # 后端服务
  prank-backend:
    build: ./backend
    container_name: prank-backend
    restart: always
    ports:
      - "5001:5001"
    environment:
      - DB_HOST=106.14.227.122
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=13524155957Qz@1
      - DB_DATABASE=freshbird
    networks:
      - prank-network

  # 前端服务
  prank-frontend:
    build: ./frontend
    container_name: prank-frontend
    restart: always
    ports:
      - "8088:80"
    depends_on:
      - prank-backend
    networks:
      - prank-network

networks:
  prank-network:
    driver: bridge

